reference: "../workflow_data/genomes/hg38_ucsc_filtered/hg38_ucsc_filtered.fa"
bed: "../snakemake/resources/bed/regions.bed"
filtered: "../workflow_data/genomes/hg38_ucsc_filtered/hg38_ucsc_filtered_genomeFile.txt"
dict: "../workflow_data/genomes/hg38_ucsc_filtered/hg38_ucsc_filtered.dict"
snpeff: "../snakemake/resources/snpeff/hg38"
dbnsfp: "../workflow_data/db/dbNSFP/dbNSFP4.1a_variant.chr2.gz"
dbsnp: "../workflow_data/db/dbSNP/resources_broad_hg38_v0_1000G_phase1_snps_high_confidence_hg38/resources_broad_hg38_v0_1000G_phase1.snps.high_confidence.hg38.vcf"


    
