#specify the samples path highlighting the name only
samples:
  MGM20-1035: samples/MGM20-1035
  MGM20-1013: samples/MGM20-1013

#specify the path of the reference genome
reference: "../workflow_data/genomes/hg19_ucsc_filtered/hg19_ucsc_filtered.fa"

#specify the path of the region of interest bed file 
bed: "../workflow_data/bed/slc2a1/slc2a1_and_antisense_hg19.bed"

#manually specify the region of interest (needed for deepvariant calling)
regions: "chr1:43389920-43450402"

#specify the path of the filtered genome file 
filtered: "../workflow_data/genomes/hg38_ucsc_filtered/hg38_ucsc_filtered_genomeFile.txt" #cerca hg19_ucsc_filtered_genomeFile.txt

#specify the path of the reference genome dictionary
dict: "../workflow_data/genomes/hg19_ucsc_filtered/hg19_ucsc_filtered.dict"

#specify the path to the snpeff database
snpeff: "../workflow_data/db/snpeff/hg19" 

#specify the path to the dbNSFP database
dbnsfp: "../workflow_data/db/dbNSFP/dbNSFP2.9.3/dbNSFP2.9.3_variant.chr1.gz"

#specify the path to the dbNSP database
dbsnp: "../workflow_data/db/dbSNP/hg19/snps/1000G_phase1.snps.high_confidence.hg19_sorted.vcf"

#specify the paths of the gene lists you want to check
genelists:
  -"lists/genelist1.txt"
  -"lists/genelist2.txt"

