## Target rules ##  ## Workflow options: single, combined, deepvariant ##

rule single:
    input:
        expand("qc/fastqc/{sample}_{num}.html", sample=config["samples"],  num=['1', '2']),
        expand("stats/{sample}_meqc_stats.txt", sample=config["samples"]),
        expand("stats/{sample}_iCoverage_output_file.xlsx", sample=config["samples"]),
        expand("csvfile/{sample}.csv", sample=config["samples"])

rule combined:
    input:
        expand("qc/fastqc/{sample}_{num}.html", sample=config["samples"],  num=['1', '2']),
        expand("stats/{sample}_meqc_stats.txt", sample=config["samples"]),
        expand("stats/{sample}_iCoverage_output_file.xlsx", sample=config["samples"]),
        "csvfile/all.csv"

rule deepvariant:
  input:
        expand("qc/fastqc/{sample}_{num}.html", sample=config["samples"],  num=['1', '2']),
        expand("stats/{sample}_meqc_stats.txt", sample=config["samples"]),
        expand("stats/{sample}_iCoverage_output_file.xlsx", sample=config["samples"]),
        "dv_csvfile/all.csv"

#rule cnv:
#   input:

#rule somatic:
#   input:

#rule mitochondrial:
#   input:

#rule rnaseq:
#   input:

#rule singlecell:
#   input:


## Modules ##

include: "rules/mapping.smk"
include: "rules/qc.smk"
include: "rules/adjusting.smk"
include: "rules/sortindex.smk"
include: "rules/scripts.smk"
include: "rules/combo_call_ann.smk"
include: "rules/single_call_ann.smk"
include: "rules/deepvariant_call_ann.smk"

