SAMPLES = ["a", "b"] #add as many letters as the number of samples you have 

## Target rules ##

rule all:
    input:
        expand("qc/fastqc/{sample}.html", sample=SAMPLES),
        expand("stats/{sample}_meqc_stats.txt", sample=SAMPLES),
        expand("stats/{sample}_iCoverage_output_file.xlsx", sample=SAMPLES),
        expand("csvfile/{sample}.csv", sample=SAMPLES),
        "csvfile/all.csv"

rule single:
    input:
        expand("qc/fastqc/{sample}.html", sample=SAMPLES),
        expand("stats/{sample}_meqc_stats.txt", sample=SAMPLES),
        expand("stats/{sample}_iCoverage_output_file.xlsx", sample=SAMPLES),
        expand("csvfile/{sample}.csv", sample=SAMPLES)

rule combined:
    input:
        expand("qc/fastqc/{sample}.html", sample=SAMPLES),
        expand("stats/{sample}_meqc_stats.txt", sample=SAMPLES),
        expand("stats/{sample}_iCoverage_output_file.xlsx", sample=SAMPLES),
        "csvfile/all.csv"

#rule cnv:
#   input:

#rule somatic:
#   input:

#rule mitochondrial:
#   input:

#include rnaseq:
#   input:

#include singlecell:
#   input:

## Modules ##

include: "rules/mapping.smk"
include: "rules/qc.smk"
include: "rules/adjusting.smk"
include: "rules/sortindex.smk"
include: "rules/scripts.smk"
include: "rules/combo_call_ann.smk"
include: "rules/single_call_ann.smk"

