SAMPLES = ["a"] #add as many letters as the number of samples you have 

## Target rules ##

rule all:
    input:
        expand("qc/fastqc/{sample}.html", sample=SAMPLES),
        expand("stats/{sample}_meqc_stats.txt", sample=SAMPLES),
        expand("stats/{sample}_iCoverage_output_file.xlsx", sample=SAMPLES),
        expand("s_sift_dbNSFP/{sample}.vcf", sample=SAMPLES),
        "sift_dbNSFP/all.vcf"

rule single:
    input:
        expand("qc/fastqc/{sample}.html", sample=SAMPLES),
        expand("stats/{sample}_meqc_stats.txt", sample=SAMPLES),
        expand("stats/{sample}_iCoverage_output_file.xlsx", sample=SAMPLES),
        expand("s_sift_dbNSFP/{sample}.vcf", sample=SAMPLES)

rule combined:
    input:
        expand("qc/fastqc/{sample}.html", sample=SAMPLES),
        expand("stats/{sample}_meqc_stats.txt", sample=SAMPLES),
        expand("stats/{sample}_iCoverage_output_file.xlsx", sample=SAMPLES),
        "sift_dbNSFP/all.vcf"

#rule cnv:
#   input:

#rule somatic:
#   input:

#rule mitochondrial:
#   input:

## Modules ##

include: "rules/mapping.smk"
include: "rules/qc.smk"
include: "rules/adjusting.smk"
include: "rules/sortindex.smk"
include: "rules/scripts.smk"
include: "rules/combo_call_ann.smk"
include: "rules/single_call_ann.smk"
