## Optional Tools ##

fastqc: True
meqc: True
icov: True 

## Files Paths ##

## Path of the samples
samples:
  #MGM20-1647: samples/MGM20-1647
  MGM20-1869: samples/MGM20-1869
  #dicitura: nome: path/to/nome (nel path avrà formato nome_num.fastq)


## Path of the reference genome
reference: "../workflow_data/genomes/hg19_ucsc_filtered/hg19_ucsc_filtered.fa"

## Path of the bed file 
bed: "../workflow_data/bed/epilepsy/3069791_epilepsy_sorted_ovl.bed"

## Path of the filtered genome file 
filtered: "../workflow_data/genomes/hg19_ucsc_filtered/hg19_ucsc_filtered_genomeFile.txt" #cerca hg19_ucsc_filtered_genomeFile.txt

## Path of the reference genome dictionary
dict: "../workflow_data/genomes/hg19_ucsc_filtered/hg19_ucsc_filtered.dict"

## Path to the Snpeff database
snpeff: "../workflow_data/db/snpeff/hg19" 

## Path to the dbNSFP database
dbnsfp: "../workflow_data/db/dbNSFP/dbNSFP2.9.3/dbNSFP2.9.3_variant.chr1.gz"

## Path to the dbNSP database
dbsnp: "../workflow_data/db/dbSNP/hg19/1000G_phase1.snps.high_confidence.hg19_sorted.vcf"

## Paths of the gene lists you want to check
genelists:
  -"lists/genelist1.txt"
  -"lists/genelist2.txt"


## Tools Parameters ##

# The java_opts param allows for additional arguments to be passed to the java compiler,
# e.g. “-Xmx4G” for one, and “-Xmx4G -XX:ParallelGCThreads=10” for two options.

# The extra param alllows for additional program arguments.

# For more inforamtion see, https://software.broadinstitute.org/gatk/documentation/article?id=11050

FastQC:
  params: ""

bwaMem:
  params:
    sort: "samtools" # Can be 'none', 'samtools' or 'picard'.
    sort_order: "coordinate"  # Can be 'queryname' or 'coordinate'.
    sort_extra:  "" # Extra args for samtools/picard.

picard_AddOrReplaceGroups:
  params: "VALIDATION_STRINGENCY=LENIENT RGLB=lib1 RGPL=ILLUMINA RGPU=unit1 RGSM=20"

# the bed file path must be hard coded
samtools_View:
  params: "-b -h -L ../workflow_data/bed/epilepsy/3069791_epilepsy_sorted_ovl.bed"

picard_MarkDuplicates:
  params: "ASSUME_SORTED=true REMOVE_DUPLICATES=false"

gatk_BaseRecalibrator:
  params:
    extra: "" 
    java_opts: "" 

gatk_ApplyBQSR:
  params:
    extra: ""  
    java_opts: ""  

picard_Sortsam:
  params:
    sort_order: "coordinate"
    extra: "VALIDATION_STRINGENCY=LENIENT"

samtools_Index: 
  params: "" 

gatk_HaplotypeCaller:
  params:
    java_opts: "-Xmx8g" 
    extra: "--standard-min-confidence-threshold-for-calling 10.0 --sample-ploidy 2 --dont-use-soft-clipped-bases"

gatk_CombineGvcfs:
  params:
    extra: "" 
    java_opts: "-Xmx8g" 

gatk_GenotypeGvcfs:
  params:
    extra: "--standard-min-confidence-threshold-for-calling 10.0 --sample-ploidy 2" # optional
    java_opts: "-Xmx4g" 

gatk_SelectVariants:
  snps:
    extra: "--select-type-to-include SNP --select-type-to-include MNP"
  indel:
    extra: "--select-type-to-include INDEL --select-type-to-include MIXED"

gatk_FilterVariants:
  snps:
    filters: {"myfilter": "QD < 2.0 || FS > 60.0 || MQ < 40.0 || MQRankSum < -12.5 || ReadPosRankSum < -8.0"}
  indels:
    filters: {"myfilter": "QD < 2.0 || FS > 200.0 || ReadPosRankSum < -20.0"}

snpeff_Annotate:
  params:
    extra: ""
    java_opts: "-Xmx8g" 

snpsift_Annotate:
  params:
    extra: ""
    java_opts: "-Xmx8g"

snpsift_dbNSFP:
  params:
    extra: "-n" # -n comprente tutti i fields tranne quelli specificati con -f
    java_opts: "-Xmx8g"

deepvariant:
  model: "wgs"     # {wgs, wes}
  regions: " --region chr1:43389920-43450402"
